# Generated by Django 3.0.3 on 2020-03-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirencelist',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Since', 'Since'), ('Football', 'Football'), ('Ecology', 'Ecology')], default='IT', max_length=8),
        ),
    ]
