# Generated by Django 3.0.3 on 2020-03-11 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_confirencelist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='user',
        ),
        migrations.AddField(
            model_name='records',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
