# Generated by Django 2.2.6 on 2020-03-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_confirencelist_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirencelist',
            name='img',
        ),
    ]
