# Generated by Django 2.2.6 on 2020-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_confirencelist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirencelist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
